/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.Relaciones;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mery Acevedo
 */
public class cuartiles extends javax.swing.JFrame {

    public  ArrayList<Relaciones> lR;
    public Double r1,r2,r3,m;
     DefaultTableModel t1,t2,t3,t4;
     SimpleDateFormat sdfe = new SimpleDateFormat("dd/MM/yyyy");
    
    /**
     * Creates new form cuartiles
     */
    public cuartiles(ArrayList<Relaciones> a) {
        this.lR=a;
        initComponents();
        this.t1= (DefaultTableModel) this.jTable1.getModel();
        this.t2= (DefaultTableModel) this.jTable2.getModel();
        this.t3= (DefaultTableModel) this.jTable4.getModel();
        this.t4= (DefaultTableModel) this.jTable5.getModel();
       this.llenar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PRIMER CUARTIL");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "dueño", "mascota", "num consulta", "doctor", "clinica", "costo", "fecha"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("SEGUNDO CUARTIL");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "dueño", "mascota", "num consulta", "doctor", "clinica", "costo", "fecha"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setText("TERCER CUARTIL");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "dueño", "mascota", "num consulta", "doctor", "clinica", "costo", "fecha"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jLabel4.setText("CUARTO CUARTIL");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "dueño", "mascota", "num consulta", "doctor", "clinica", "costo", "fecha"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    // End of variables declaration//GEN-END:variables


public void generarC(){
 
    Double mayor=0.0;
    
    for (int i = 0; i < this.lR.size(); i++) {
        if (this.lR.get(i).getoConsulta().getMonto()>mayor) {
            mayor=this.lR.get(i).getoConsulta().getMonto();
        }
        
    }
    m=mayor;
    r1=mayor*0.25;
    r2=mayor*0.50;
    r3=mayor*0.75;
}

public void llenar(){
    this.generarC();
   
    for (int i = 0; i < this.lR.size(); i++) {
        if (this.lR.get(i).getoConsulta().getMonto()>0 && this.lR.get(i).getoConsulta().getMonto()<=r1) {
            String[] stt1={this.lR.get(i).getDuennio().getNombre(),
                this.lR.get(i).getoMascota().getNombre(),
                this.lR.get(i).getoConsulta().getNumC(),
                this.lR.get(i).getVeterinario().getNombre(),
                    this.lR.get(i).getoSucursal().getNombre(),
                    String.valueOf(this.lR.get(i).getoConsulta().getMonto()),
                    sdfe.format(this.lR.get(i).getoConsulta().getFechaHora())
            };
            t1.addRow(stt1);
        }else if(this.lR.get(i).getoConsulta().getMonto()>r1 && this.lR.get(i).getoConsulta().getMonto()<=r2){
            String[] stt1={this.lR.get(i).getDuennio().getNombre(),
                this.lR.get(i).getoMascota().getNombre(),
                this.lR.get(i).getoConsulta().getNumC(),
                this.lR.get(i).getVeterinario().getNombre(),
                    this.lR.get(i).getoSucursal().getNombre(),
                    String.valueOf(this.lR.get(i).getoConsulta().getMonto()),
                    sdfe.format(this.lR.get(i).getoConsulta().getFechaHora())
            };
            t2.addRow(stt1);
        }else if(this.lR.get(i).getoConsulta().getMonto()>r2 && this.lR.get(i).getoConsulta().getMonto()<=r3){
            String[] stt1={this.lR.get(i).getDuennio().getNombre(),
                this.lR.get(i).getoMascota().getNombre(),
                this.lR.get(i).getoConsulta().getNumC(),
                this.lR.get(i).getVeterinario().getNombre(),
                    this.lR.get(i).getoSucursal().getNombre(),
                    String.valueOf(this.lR.get(i).getoConsulta().getMonto()),
                    sdfe.format(this.lR.get(i).getoConsulta().getFechaHora())
            };
            t3.addRow(stt1);
        }else {
            String[] stt1={this.lR.get(i).getDuennio().getNombre(),
                this.lR.get(i).getoMascota().getNombre(),
                this.lR.get(i).getoConsulta().getNumC(),
                this.lR.get(i).getVeterinario().getNombre(),
                    this.lR.get(i).getoSucursal().getNombre(),
                    String.valueOf(this.lR.get(i).getoConsulta().getMonto()),
                    sdfe.format(this.lR.get(i).getoConsulta().getFechaHora())
            };
            t4.addRow(stt1);
        }
        
        
        
    }
}



}
