/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.*;


import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ordenamiento.orderCa;
import ordenamiento.orderCd;
import ordenamiento.orderMa;
import ordenamiento.orderMd;
import ordenamiento.orderNa;
import ordenamiento.orderNb;

/**
 *
 * @author Mery Acevedo
 */
public class frmPagos extends javax.swing.JFrame {

    private ArrayList<clinica> lCli;
    private ArrayList<Relaciones> lRel;
    DefaultTableModel mdlTabla;
    private Date fecha;
    SimpleDateFormat sdfe = new SimpleDateFormat("dd/MM/yyyy");
    double mont;
    private int cont=1;
            
    public frmPagos() {
        initComponents();
        this.jLabel28.setText(String.valueOf(cont));
        fecha=new Date();
        this.jLabel26.setText(sdfe.format(fecha));
        this.mdlTabla= (DefaultTableModel) this.jTable1.getModel();
        this.lCli=new ArrayList<>();
        this.lRel=new ArrayList<>();
        this.simularDatos();
        this.cargarClinicas();
        this.cargaTabla();
        this.jTextField11.setVisible(false);
        this.jLabel15.setVisible(false);
       // this.jLabel12.setVisible(false);
       
        //this.jLabel22.setVisible(false);
        this.jLabel23.setVisible(false);
      //  this.jTextField6.setVisible(false);
        this.jTextField7.setVisible(false);
    }
    
    
    private void cargaTabla()
    {     
        this.mdlTabla.setRowCount(0);
        for(int j=0; j<this.lRel.size(); j++)
        {
            String[] registro = { 
                
                this.lRel.get(j).getDuennio().getNombre(),
                this.lRel.get(j).getoMascota().getNombre(),
                this.lRel.get(j).getoConsulta().getNumC(),
                Double.toString(this.lRel.get(j).getoConsulta().getMonto()),
                this.lRel.get(j).getVeterinario().getNombre()+ " " +this.lRel.get(j).getVeterinario().getApellido(),
                this.lRel.get(j).getoSucursal().getNombre(),
                   this.sdfe.format( this.lRel.get(j).getoConsulta().getFechaHora())
            };
            this.mdlTabla.addRow(registro);
        }
    }

    private void simularDatos()
    {
       //inicializar las sucursales
        //sucursal 1
        this.lCli.add(new clinica("San salvador","Blv Los Proceres", 
                              new Persona("Juan", "Perez"),
                              new ArrayList<>()));
        this.lCli.get(0).getlCaj().add(new Persona("Miguel", "Benavides"));
        this.lCli.get(0).getlCaj().add(new Persona("Samuel", "Paniagua"));
        this.lCli.get(0).getlCaj().add(new Persona("Ivan", "Sandoval"));
        
        //sucursal 2
        this.lCli.add(new clinica("santa Tecla","parque San Martin",
                         new Persona("José", "Rodríguez"),
                         new ArrayList<>()));
        this.lCli.get(1).getlCaj().add(new Persona("Carolina", "Solito"));
        this.lCli.get(1).getlCaj().add(new Persona("Bryan", "Solis"));
        this.lCli.get(1).getlCaj().add(new Persona("José", "Cabrera"));
        
        //sucursal 3

        this.lCli.add(new clinica("Agencia San Miguel","Centro",
                         new Persona("Amelia", "Rivas"),
                         new ArrayList<>())); 
        this.lCli.get(2).getlCaj().add(new Persona("Amanda", "Castro"));
        this.lCli.get(2).getlCaj().add(new Persona("Arnold", "Arita"));
        this.lCli.get(2).getlCaj().add(new Persona("Bertha", "Rodríguez"));
    }      
    
    private void cargarClinicas()
    {
       this.jComboBox2.removeAllItems();
       for(int i=0; i<this.lCli.size(); i++)
       {
           this.jComboBox2.addItem(this.lCli.get(i).getNombre());
       }    
    }  
    
    private void cargarVeterinarios(int pIdSuc)
    {
       this.jComboBox1.removeAllItems();
       for(int i=0; i<this.lCli.get(pIdSuc).getlCaj().size(); i++)
       {
           this.jComboBox1.addItem(this.lCli.get(pIdSuc).getlCaj().get(i).getNombre()+" "+
                                   this.lCli.get(pIdSuc).getlCaj().get(i).getApellido());
       }
    } 
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtProm = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        lblmonto2 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "dueño", "mascota", "consulta", "Monto", "doctor", "clinica", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("DUEÑO:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("MASCOTA:");

        jLabel7.setText("Edad:");

        jLabel13.setText("Fecha:");

        jLabel15.setText("Monto:");

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel16.setText("CONSULTA");

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel17.setText("SUCURSAL:");

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("Pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("  Estadísticas de pagos:  ");

        jLabel14.setText("Mínimo:");

        txtMin.setEditable(false);
        txtMin.setBackground(new java.awt.Color(224, 224, 224));
        txtMin.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel19.setText("Máximo:");

        txtMax.setEditable(false);
        txtMax.setBackground(new java.awt.Color(224, 224, 224));
        txtMax.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel20.setText("Total:");

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(224, 224, 224));
        txtTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel21.setText("Promedio:");

        txtProm.setEditable(false);
        txtProm.setBackground(new java.awt.Color(224, 224, 224));
        txtProm.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProm, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtProm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel18.setText("Doctor:");

        jLabel9.setText("Nombre:");

        jLabel11.setText("Tipo:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "control", "limpieza", "emergencia" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jLabel12.setText("Monto:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dueño", "mascota", "costo" }));

        jButton2.setText("ver ascendente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ver descendente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel8.setText("por");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "dueño", "mascota", "clinica", "doctor", "monto" }));
        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel22.setText("nombre");

        jLabel23.setText("jLabel23");

        jLabel24.setText("BUSQUEDA:");

        jButton5.setText("ver cuartiles");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel25.setText("numero consulta:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                            .addComponent(jTextField2)))
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel12)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblmonto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                    .addComponent(jLabel25)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(jLabel11)
                                                                    .addGap(18, 18, 18)
                                                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel13)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel15)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(jLabel16))
                                                        .addGap(0, 78, Short.MAX_VALUE)))))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel24)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8)
                        .addGap(43, 43, 43)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jButton5)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel9)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(13, 13, 13)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10))
                                .addGap(5, 5, 5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(lblmonto2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jButton5))
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        this.cargarVeterinarios(this.jComboBox2.getSelectedIndex());
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // crear transacción
        
        if (this.jComboBox3.getSelectedIndex()==3) {
            try{
            mont=Double.parseDouble(this.jTextField11.getText());
            
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null,"error en monto");
            mont=0.0;
        }
        }
        if (mont>0 ) {
            this.lRel.add(new Relaciones(
            new Persona(this.jTextField1.getText().trim(), // pagador
                        this.jTextField2.getText().trim()), 
                
            new animal(this.jTextField4.getText().trim(), //receptor
                        String.valueOf(this.jSpinner1.getValue())
                        ), 
                
            this.lCli.get(this.jComboBox2.getSelectedIndex()), // clinica
this.lCli.get(this.jComboBox2.getSelectedIndex()).getlCaj().get(this.jComboBox1.getSelectedIndex()),// veterinario
        //-------------------------------------------------------------------------------------------        
            new Consulta(String.valueOf(this.cont), // consulta
                    this.jComboBox3.getSelectedIndex(),
                        this.fecha,
                    
                        this.mont)
            ));
        this.cont++;
        this.cargaTabla(); // recargar la tabla
        this.txtMin.setText(Double.toString(this.minimo()));
        this.txtMax.setText(Double.toString(this.maximo()));
        this.txtProm.setText(Double.toString(this.promedio()));
        this.txtTotal.setText(Double.toString(this.sumatoria()));
             this.jLabel28.setText(String.valueOf(cont));
        }else{
            JOptionPane.showMessageDialog(null, "ERROR monto sin datos o dato incorrecto \n RECUERDE AGREGAR UN TIPO ");}
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new cuartiles(this.lRel).setVisible(true);
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        switch (this.jComboBox4.getSelectedIndex()) {
            case 0:
               orderNa ONA= new orderNa();
               this.lRel.sort(ONA);
               this.cargaTabla();
                //nombre
                break;
            case 1:
                orderMa OMA = new orderMa();
                this.lRel.sort(OMA);
                this.cargaTabla();
                //mascota
                break;
            case 2:
                orderCa OCA=new orderCa();
                this.lRel.sort(OCA);
                this.cargaTabla();
                //monto
                break;
            default:
                
        }
        


// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        switch (this.jComboBox4.getSelectedIndex()) {
            case 0:
               orderNb ONA= new orderNb();
               this.lRel.sort(ONA);
               this.cargaTabla();
                //nombre
                break;
            case 1:
                orderMd OMA = new orderMd();
                this.lRel.sort(OMA);
                this.cargaTabla();
                //mascota
                break;
            case 2:
                orderCd OCA=new orderCd();
                this.lRel.sort(OCA);
                this.cargaTabla();
                //monto
                break;
            default:
                
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        // TODO add your handling code here:
//        
//        switch (this.jComboBox5.getSelectedIndex()) {
//            case 0:
//                break;
//            case 1:
//                this.jLabel22.setText("nombre");
//        this.jLabel22.setVisible(true); 
//        this.jTextField6.setVisible(true);
//        this.jLabel23.setVisible(false);
//        this.jTextField7.setVisible(false);
//                break;
//                
//            case 2:
//               this.jLabel22.setText("nombre");
//        this.jLabel22.setVisible(true); 
//        this.jTextField6.setVisible(true);
//        this.jLabel23.setVisible(false);
//        this.jTextField7.setVisible(false);
//                break;
//                
//            case 3:
//                this.jLabel22.setText("nombre");
//        this.jLabel22.setVisible(true); 
//        this.jTextField6.setVisible(true);
//        this.jLabel23.setVisible(false);
//        this.jTextField7.setVisible(false);
//                break;
//            case 4: this.jLabel22.setText("nombre");
//        this.jLabel22.setVisible(true); 
//        this.jTextField6.setVisible(true);
//        this.jLabel23.setVisible(false);
//        this.jTextField7.setVisible(false);
//                break;
//            case 5:
//                 this.jLabel22.setText("minimo");
//        this.jLabel22.setVisible(true); 
//        this.jTextField6.setVisible(true);
//        this.jLabel23.setText("maximo");
//        this.jLabel23.setVisible(true);
//        this.jTextField7.setVisible(true);
//                break;
//            default:
//                throw new AssertionError();
//        }
        
        
        
        if (this.jComboBox5.getSelectedIndex()< 5) {
           this.jLabel22.setText("nombre");
        this.jLabel22.setVisible(true); 
        this.jTextField6.setVisible(true);
        this.jLabel23.setVisible(false);
        this.jTextField7.setVisible(false);
        }else{
            
           this.jLabel22.setText("minimo");
        this.jLabel22.setVisible(true); 
        this.jTextField6.setVisible(true);
        this.jLabel23.setText("maximo");
        this.jLabel23.setVisible(true);
        this.jTextField7.setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       this.mdlTabla.getDataVector().removeAllElements();
       Relaciones r=null ;
       String b;
        switch (this.jComboBox5.getSelectedIndex()) {
            case 1:
                b=this.jTextField6.getText();
                for (Relaciones object : this.lRel) {
                    if (object.getDuennio().getNombre().equals(b)) {
                        r=object;
                        break;
                    }
                }
                break;
            case 2:
                b=this.jTextField6.getText();
                for (Relaciones object : this.lRel) {
                    if (object.getoMascota().getNombre().equals(b)) {
                        r=object;
                        break;
                    }
                }
                break;
            case 3:
                b=this.jTextField6.getText();
                for (Relaciones object : this.lRel) {
                    if (object.getoSucursal().getNombre().equals(b)) {
                        
                    }
                }
                break;
            case 4:
                b=this.jTextField6.getText();
                for (Relaciones object : this.lRel) {
                    if (object.getVeterinario().getNombre().equals(b)) {
                        r=object;
                        break;
                    }
                }
                break;
            case 5:
                try{
                Double b1=Double.parseDouble(this.jTextField6.getText());
                Double b2=Double.parseDouble(this.jTextField7.getText());
                //String b=this.jTextField6.getText();
                for (Relaciones o : this.lRel) {
                    if (o.getoConsulta().getMonto()>b1 && o.getoConsulta().getMonto()<b2) {
                        String[] registro = { 
                
                o.getDuennio().getNombre()+ " " + o.getDuennio().getApellido(),
                o.getoMascota().getNombre(),
                o.getoConsulta().getNumC(),
                Double.toString(o.getoConsulta().getMonto()),
                o.getVeterinario().getNombre()+ " " +o.getVeterinario().getApellido(),
                o.getoSucursal().getNombre(),
                   this.sdfe.format( o.getoConsulta().getFechaHora())
            };
            this.mdlTabla.addRow(registro);
                    }
                }
                
                  
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "error ingrese datos numericos");
                }
                break;
        }
        if(r!=null){
        String[] registro = { 
                
                r.getDuennio().getNombre()+ " " + r.getDuennio().getApellido(),
                r.getoMascota().getNombre()+ " " + r.getoMascota().getEdad(),
                r.getoConsulta().getNumC(),
                Double.toString(r.getoConsulta().getMonto()),
                r.getVeterinario().getNombre()+ " " +r.getVeterinario().getApellido(),
                r.getoSucursal().getNombre(),
                   this.sdfe.format( r.getoConsulta().getFechaHora())
            };
            this.mdlTabla.addRow(registro);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
        switch (this.jComboBox3.getSelectedIndex()) {
            case 1:
                this.jLabel15.setVisible(false);
                this.jTextField11.setVisible(false);
                this.jLabel12.setVisible(true);
                this.lblmonto2.setVisible(true);
                this.mont=12;
                this.lblmonto2.setText("$ 12.00");
                break;
            case 2:
                this.jLabel15.setVisible(false);
                this.jTextField11.setVisible(false);
                this.jLabel12.setVisible(true);
                this.lblmonto2.setVisible(true);
                this.mont=9;
                this.lblmonto2.setText("$ 9.00");
                break;
            case 3:
                this.jLabel12.setVisible(false);
                this.lblmonto2.setVisible(false);
                this.jLabel15.setVisible(true);
                this.jTextField11.setVisible(true);
                //this.mont=Double.parseDouble(this.jTextField11.getText().toString());
                
                break;
            default:
                throw new AssertionError();
        }
        
        
        
        
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private double minimo()
    {
       double min=0;
       if(this.lRel.size()>0)
       {
           min=this.lRel.get(0).getoConsulta().getMonto();
           for(int i=1; i<this.lRel.size(); i++)
           {
               if(min>this.lRel.get(i).getoConsulta().getMonto())
                   min=this.lRel.get(i).getoConsulta().getMonto();
           }
       }
       return min;
    }
    
    private double maximo()
    {
        
       double max=0;
       if(this.lRel.size()>0)
       {
           max=this.lRel.get(0).getoConsulta().getMonto();
           for(int i=1; i<this.lRel.size(); i++)
           {
               if(max<this.lRel.get(i).getoConsulta().getMonto())
                   max=this.lRel.get(i).getoConsulta().getMonto();
           }
       }
       return max;
    }
    
    private double promedio()
    {
        double prom=(this.sumatoria()/this.lRel.size());
        prom*=100;
        prom= Math.round(prom);
        return (prom/100);
    }
    
    private double sumatoria()
    {
        double total=0;
        for(int i=0; i<this.lRel.size(); i++)
        {
             total+= this.lRel.get(i).getoConsulta().getMonto();
        }
        total*=100;
        total= Math.round(total);
        return (total/100);
    }
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblmonto2;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtProm;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
